"""edited datetime types

Revision ID: 93aed3013246
Revises: e79addac30ff
Create Date: 2021-12-09 15:52:18.746775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93aed3013246'
down_revision = 'e79addac30ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Messages', sa.Column('datetime', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('Messages', 'time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Messages', sa.Column('time', sa.DATE(), nullable=True))
    op.drop_column('Messages', 'datetime')
    # ### end Alembic commands ###
